# Generated by Django 4.0.1 on 2022-01-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcadmics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_no', models.CharField(max_length=10)),
                ('Maths', models.CharField(max_length=10)),
                ('Physics', models.CharField(max_length=10)),
                ('Chemistry', models.CharField(max_length=10)),
                ('Biology', models.CharField(max_length=10)),
                ('English', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=20)),
                ('Clas', models.CharField(max_length=20)),
                ('School', models.CharField(max_length=40)),
                ('Mobile', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
